### ISSUE TITLE
Failed to build CPPUTEST in mri

### ISSUE THREAD

**Issue by jaredcjrtw** [adamgreen/CppUTest#1]
I type the command `make clean all` in `mri`,but it failed to build the tests.

The error messages are as follows:

```
Building lib/host/libCppUTest.a
Building CPPUTEST_tests
Runnning CPPUTEST_tests
make: CPPUTEST_tests: Command not found
makefile:199: recipe for target 'RUN_CPPUTEST_TESTS' failed
make: *** [RUN_CPPUTEST_TESTS] Error 127
```

Thanks

**Comment by adamgreen** [comment]
The makefile which is failing is in the MRI project and not this CPPUTEST submodule.  Just the code is here.  Reactivate the bug in the MRI project and I will look at it there.

**Comment by adamgreen** [comment]
I have actually fixed the makefile in the MRI project.
